### ISSUE TITLE
Runtime package on NPM is missing readme

### ISSUE THREAD

**Issue by sharwell** [tunnelvisionlabs/antlr4ts#247]
See the [antlr4ts](https://www.npmjs.com/package/antlr4ts) package on npmjs.com.

**Comment by BurtHarris** [comment]
Working hypothesis:  the reason we aren't seeing a readme on the NPM web site is that we publish the runtime to NPM from **target/src**, at least that's where the real **package.json** for the runtime seems to live.   Based on that, I'm thinking the fix is to include in the build a step that copies **README.md** from the root directory to **target/src**.

**Comment by BurtHarris** [comment]
I accidentally pushed a change to the main repository.   The update causes the README.md (and LICENSE) from the root directory to get copied into **target/src** at build time.   I think I've implemented this in a cross-platform friendly way (using an NPM module named CPY).
