### ISSUE TITLE
v4.7 support

### ISSUE THREAD

**Issue by generateui** [tunnelvisionlabs/antlr4ts#373]
Last time I checked, the typescript target only supported v4.6. What's the story on support for v4.7? I need v4.7 since I need the extended unicode support which I use in my syntax. I'm able to contribute somewhat to get it working, but it would be really great if some pointers can be given.

**Comment by sharwell** [comment]
> I need the extended unicode support which I use in my syntax

👍 This is very helpful information, since essentially everyone else can continue using 4.6 without much problem. 

I haven't evaluated the difficulty of incorporating the 4.7 changes in this target. It was a very big challenge for the (optimized) C# target, but the (optimized) Java target which the TypeScript target is based on is already complete. Hopefully I can find some time over the holiday weekend to investigate.

**Comment by mike-lischke** [comment]
Would be very nice if the interpreter data addition from me makes it into the TS target. Currently I have to duplicate the ATNDesializer because the TS target uses a different ATN structure and cannot read the generated interpreter data from the standard ANTLR4 tool.
